Homework 01, Exercise 01
LScheib/oose24 pull request #2
Opened 2024-04-29 21:25 UTC by LScheib

2024-04-29 21:51 UTC, LScheib commented on src/homework_01/Exercise_1_1.js
> +        return `${roleProf.getInfo.call(this)}`;
I tried to add the position in both overrides before, which resulted in it appearing twice in the output, because getInfo() calls getDescription() in the roleProf object. I am not sure, whether this implementation looks as they intended it to look like according to the exercise description, but it works and results in a correct output on the console.

2024-04-30 09:10 UTC, ililikakis requested changes

2024-04-30 09:10 UTC, ililikakis commented on src/homework_01/Exercise_1_1.js
> +        return `${roleProf.getInfo.call(this)}`;
I'm not sure about that either. I'll have a look at it later.

2024-04-30 09:10 UTC, ililikakis commented on src/homework_01/Exercise_1_1.js
> +console.log(roleHeadDeptAlice.getInfo());
```makeProf ()```, ```makeHeadExamBoard ()```, and ```makeHeadDept ()``` do pretty much the same thing. Reduce them to one.

```suggestion
function makeRole(person, role, chair, positionKind, level) {
    let newRole = clone(role);

    // Set the person object as the prototype of the professor object
    newRole.__proto__ = person;

    // Assign chair property
    newRole.chair = chair;

    // Validate positionKind and level
    newRole.positionKind = validatePositionKind(positionKind);
    newRole.level = validateLevel(level);

    return newRole;
}

let roleProfAlice = makeRole(alice, roleProf, "software engineering", "full professor", "W2");
console.log(roleProfAlice.getInfo());

let roleHeadExamBoardAlice = makeRole(alice, roleHeadExamBoard, "software engineering", "full professor", "W2");
console.log(roleHeadExamBoardAlice.getInfo());

let roleHeadDeptAlice = makeRole(alice, roleHeadDept, "software engineering", "full professor", "W2");
console.log(roleHeadDeptAlice.getInfo());
```

2024-05-01 10:16 UTC, LScheib commented on oose24.iml
You're probably right. I thought that this file might be needed if you want to open the project in IntelliJ or WebStorm after checking out this branch.

2024-05-01 11:39 UTC, LScheib commented on src/homework_01/Exercise_1_1.js
> +        return `${roleProf.getInfo.call(this)}`;
Let's just leave it like this.

2024-05-01 11:45 UTC, LScheib commented
@ililikakis In my opinion, this is finished. If you agree, click on "Resolve conversation" and then go ahead to merge the branch.

2024-05-02 08:59 UTC, ililikakis commented on oose24.iml
Hmm... ok, if it makes your work easier we can leave it. But configs for an IDE shouldn't really belong in the remote.

2024-05-02 09:02 UTC, ililikakis commented on src/homework_01/Exercise_1_1.js
> +        return `${roleProf.getInfo.call(this)}`;
Yeah, should be fine.

2024-05-02 09:09 UTC, merged