HW 01, EX 02
LScheib/oose24 pull request #3
Opened 2024-04-30 14:21 UTC by ililikakis

2024-05-01 13:01 UTC, LScheib requested changes
Apart from one section where I would make small changes (although that's more a matter of taste), very good. Thank you!

2024-05-02 08:24 UTC, ililikakis commented on src/homework_01/exercise_2/Main.java
> +        System.out.println(tutor.getName() + ", " + student.getSubject() + ", " + tutor.getSalary());
looks good

2024-05-02 09:29 UTC, ililikakis commented
Sorry, the last commit was added to the wrong branch. But since it's done: Please add yourself to `contributors.txt`.

2024-05-02 20:10 UTC, LScheib submitted a review, later dismissed

2024-05-02 20:42 UTC, merged